export const SPEEDY_CHOW = "Speedy Chow"
export const MODERN_ADMIN_PANEL = "Modern admin panel"
export const DASHBOARD = "Dashboard"
export const USERS = "Users"
export const ADD_PRODUCT="Add Product"
export const EDIT_PRODUCT="Edit Product"
export const ADD_USER="Add User"
export const ORDER ="Orders"