export const BASE_URL = "http://localhost:3000/"
export const PRODUCT = "product/" 
export const USER = "user/"
export const FETCH_USER = "user/all"
export const FETCH_Category="category"
export const CREATE_USER="auth/signUp"